# Generated by Django 3.2.9 on 2021-11-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_alter_rider_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='member.customer')),
            ],
        ),
    ]
