# Generated by Django 3.2.9 on 2021-11-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderapply',
            name='cus_orderer',
            field=models.CharField(blank=True, max_length=20, verbose_name='주문자 아이디'),
        ),
    ]
