# Generated by Django 3.2.9 on 2021-11-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderrequest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderapply',
            name='order_product',
        ),
    ]
