# Generated by Django 3.2.9 on 2021-11-19 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('orderrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderapply',
            name='rider_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.rider', verbose_name='라이더 이름'),
        ),
    ]
