# Generated by Django 3.2.9 on 2021-11-17 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderapply',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='수량'),
        ),
    ]
