# Generated by Django 3.2.9 on 2021-11-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderapply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='주문 요청 시간'),
        ),
    ]
