# Generated by Django 3.2.9 on 2021-11-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='introduction',
            field=models.TextField(default='text', max_length=200, verbose_name='소개'),
            preserve_default=False,
        ),
    ]
