# Generated by Django 3.2.9 on 2021-11-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderapply',
            name='introduction',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
