# Generated by Django 3.2.9 on 2021-11-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderrequest', '0002_alter_product_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='products',
            field=models.CharField(choices=[('A', '파워에이드'), ('B', '허쉬초코우유'), ('C', '초콜렛'), ('D', '청국장'), ('E', '부대찌개')], max_length=6),
        ),
    ]
