# Generated by Django 3.2.9 on 2021-11-14 12:25

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orderrequest', '0002_rider_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='address_rider',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_unique',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nickname',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sig_date_cus',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date signup customer'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='introduction',
            field=models.TextField(max_length=200, null=True, verbose_name='소개'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='nickname',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_nickname', to='orderrequest.customer'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='sig_date_rider',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date signup rider'),
        ),
    ]
