# Generated by Django 3.2.9 on 2021-11-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderrequest', '0002_rider_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='introduction',
        ),
    ]
