# Generated by Django 3.2.9 on 2021-11-19 16:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
        ('orderrequest', '0002_alter_orderapply_rider_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_date', models.DateTimeField(auto_now=True, verbose_name='평가 날짜')),
                ('speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='스피드')),
                ('fresh', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='신선도')),
                ('accuracy', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='정확도')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='평가 고객')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.rider', verbose_name='평가 라이더')),
            ],
        ),
        migrations.CreateModel(
            name='EvalCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_date', models.DateTimeField(auto_now=True, verbose_name='평가 날짜')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)], verbose_name='평가 점수')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='평가 고객')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.rider', verbose_name='평가 라이더')),
            ],
        ),
    ]
