# Generated by Django 3.2.9 on 2021-11-18 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('orderrequest', '0002_alter_orderapply_cus_orderer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderapply',
            name='cus_orderer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ord', to='member.customer', verbose_name='주문자 아아디'),
        ),
    ]
