# Generated by Django 3.2.9 on 2021-11-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderrequest', '0003_alter_product_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rider_area',
            field=models.CharField(blank=True, choices=[('GG', '경기도'), ('SL', '서울시'), ('CC', '충청도'), ('GS', '경상도'), ('GW', '강원도'), ('JL', '전라도'), ('JJ', '제주도')], max_length=2, verbose_name='배달 지역'),
        ),
        migrations.AlterField(
            model_name='product',
            name='products',
            field=models.CharField(choices=[('A', '파워에이드'), ('B', '허쉬초코우유'), ('C', '초콜렛'), ('D', '청국장'), ('E', '부대찌개')], max_length=1),
        ),
    ]
