# Generated by Django 3.2.9 on 2021-11-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderrequest', '0003_auto_20211114_2125'),
        ('orderrequest', '0003_remove_rider_introduction'),
    ]

    operations = [
    ]
