# Generated by Django 3.2.9 on 2021-11-19 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderrequest', '0004_auto_20211120_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalcustomer',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='평가 점수'),
        ),
    ]
