# Generated by Django 3.2.9 on 2021-11-18 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderrequest', '0004_merge_20211116_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orderrequest.customer')),
            ],
        ),
    ]
