# Generated by Django 3.2.9 on 2021-11-17 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderrequest', '0004_auto_20211117_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderapply',
            name='active',
        ),
        migrations.AddField(
            model_name='orderapply',
            name='price',
            field=models.PositiveSmallIntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='orderapply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록시간'),
        ),
        migrations.AlterField(
            model_name='orderapply',
            name='product',
            field=models.CharField(max_length=15, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='orderapply',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='수량'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
