# Generated by Django 3.2.9 on 2021-11-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderrequest', '0005_auto_20211117_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderapply',
            name='sale_store',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='구매장소'),
        ),
    ]
