# Generated by Django 3.2.9 on 2021-11-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderrequest', '0005_alter_orderapply_rider_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderapply',
            name='rider_selected',
            field=models.CharField(blank=True, max_length=20, verbose_name='라이더 이름'),
        ),
    ]
