# Generated by Django 3.2.9 on 2021-11-18 12:11

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=20, verbose_name='주문자')),
                ('cus_address', models.CharField(max_length=250, verbose_name='주문자 주소')),
                ('order_product', multiselectfield.db.fields.MultiSelectField(choices=[('N', 'Null'), ('E', 'Egg'), ('M', 'Milk'), ('R', 'Rice'), ('W', 'Water')], max_length=9, verbose_name='주문 목록')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='주문 요청 시간')),
                ('cus_call', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='안심번호')),
                ('order_message', models.TextField(max_length=1000, verbose_name='요청사항')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
