# Generated by Django 3.2.9 on 2021-11-13 15:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='rider_area',
            field=models.CharField(choices=[('GG', '경기도'), ('SL', '서울시'), ('CC', '충청도'), ('GS', '경상도'), ('GW', '강원도'), ('JL', '전라도'), ('JJ', '제주도')], max_length=2, verbose_name='배달 지역'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='rider_vehicle',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NL', '뚜벅이'), ('CR', '차'), ('BC', '자전거'), ('AB', '오토바이')], max_length=11, verbose_name='배달 수단'),
        ),
    ]
