# Generated by Django 3.2.9 on 2021-11-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20211112_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='fresh',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='speed',
        ),
    ]
