# Generated by Django 3.2.9 on 2021-11-14 12:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20211113_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='bankbook',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='통장 사본 유무'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='license',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='면허증 여부'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='min_delivery_amount',
            field=models.IntegerField(blank=True, verbose_name='최소 주문 금액'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='rider_area',
            field=models.CharField(blank=True, choices=[('GG', '경기도'), ('SL', '서울시'), ('CC', '충청도'), ('GS', '경상도'), ('GW', '강원도'), ('JL', '전라도'), ('JJ', '제주도')], max_length=2, verbose_name='배달 지역'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='rider_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='라이더 아이디'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='rider_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='라이더 이름'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='rider_pw',
            field=models.CharField(blank=True, max_length=20, verbose_name='라이더 비밀번호'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='rider_vehicle',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NL', '뚜벅이'), ('CR', '차'), ('BC', '자전거'), ('AB', '오토바이')], max_length=11, verbose_name='배달 수단'),
        ),
    ]
