# Generated by Django 3.2.9 on 2021-11-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20211114_0056'),
        ('delivery', '0004_auto_20211114_2125'),
    ]

    operations = [
    ]
