# Generated by Django 3.2.9 on 2021-11-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20211116_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='rider_id',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='rider_pw',
        ),
    ]
