# Generated by Django 3.2.9 on 2021-11-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_auto_20211117_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='rider_name',
            field=models.TextField(blank=True, max_length=100, verbose_name='라이더 이름'),
        ),
    ]
