# Generated by Django 3.2.9 on 2021-11-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_rider_rider_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rider',
        ),
    ]
