# Generated by Django 3.2.9 on 2021-11-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_auto_20211118_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='fresh',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='speed',
        ),
    ]
