# Generated by Django 3.2.9 on 2021-11-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rider',
            options={'verbose_name': '라이더 가입 정보'},
        ),
    ]
