# Generated by Django 3.2.9 on 2021-11-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cus_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='고객 프로필 사진'),
        ),
        migrations.AddField(
            model_name='rider',
            name='rider_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='라이더 프로필 사진'),
        ),
    ]
