# Generated by Django 3.2.9 on 2021-11-12 15:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cus_call',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cus_pw',
            field=models.CharField(max_length=200, verbose_name='고객 비밀번호'),
        ),
    ]
