# Generated by Django 3.2.9 on 2021-11-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20211119_1754'),
        ('member', '0003_alter_customer_email'),
    ]

    operations = [
    ]
