# Generated by Django 3.2.9 on 2021-11-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20211113_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cus_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cus_pw',
        ),
        migrations.AlterField(
            model_name='user',
            name='cus_address',
            field=models.TextField(blank=True, max_length=100, verbose_name='고객 주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cus_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='고객 아이디'),
        ),
    ]
