# Generated by Django 3.2.9 on 2021-11-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_merge_20211119_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='accuracy',
            field=models.IntegerField(blank=True, null=True, verbose_name='정확도'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='fresh',
            field=models.IntegerField(blank=True, null=True, verbose_name='신선도'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='speed',
            field=models.IntegerField(blank=True, null=True, verbose_name='스피드'),
        ),
    ]
