# Generated by Django 3.2.9 on 2021-11-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20211119_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_nickname',
            field=models.CharField(blank=True, max_length=20, verbose_name='고객 별명'),
        ),
    ]
