# Generated by Django 3.2.9 on 2021-11-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_customer_cus_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='min_delivery_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='최소 주문 금액'),
        ),
    ]
