# Generated by Django 3.2.9 on 2021-11-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='register_data',
        ),
        migrations.AddField(
            model_name='user',
            name='cus_address',
            field=models.TextField(blank=True, max_length=100, verbose_name='고객 주소'),
        ),
        migrations.AddField(
            model_name='user',
            name='cus_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='고객 아이디'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
