# Generated by Django 3.2.9 on 2021-11-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20211114_0056'),
        ('member', '0010_auto_20211114_2128'),
    ]

    operations = [
    ]
