# Generated by Django 3.2.9 on 2021-11-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20211118_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='accuracy',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], max_length=1, null=True, verbose_name='정확도'),
        ),
        migrations.AddField(
            model_name='rider',
            name='fresh',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], max_length=1, null=True, verbose_name='신선도'),
        ),
        migrations.AddField(
            model_name='rider',
            name='speed',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], max_length=1, null=True, verbose_name='스피드'),
        ),
    ]
